site_name: 30 Sec of code
site_url: ''
theme:
  name: material
  logo: https://static.footloose.io/media_assets/logos/nyana-logo-light.png
  palette:
    primary: deep purple
    accent: deep purple
    scheme: default
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - navigation.tracking
extra_css:
  - https://static.footloose.io/customCss/extra.css
  - ''
  - https://unpkg.com/x-data-spreadsheet@1.1.5/dist/xspreadsheet.css
  - https://unpkg.com/x-data-spreadsheet@1.1.5/dist/xspreadsheet.css
extra_javascript:
  - https://static.footloose.io/customJavascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - ''
  - https://unpkg.com/x-data-spreadsheet@1.1.5/dist/xspreadsheet.js
  - >-
    https://s3.ap-south-1.amazonaws.com/static.footloose.io/customJavascripts/worksheetParser.js
  - >-
    https://s3.ap-south-1.amazonaws.com/static.footloose.io/abstraction/parser.js
  - https://unpkg.com/x-data-spreadsheet@1.1.5/dist/xspreadsheet.js
  - >-
    https://s3.ap-south-1.amazonaws.com/static.footloose.io/customJavascripts/worksheetParser.js
  - >-
    https://s3.ap-south-1.amazonaws.com/static.footloose.io/abstraction/parser.js
copyright: >-
  Built with <a href="https://nyana.brahma.ai">Nyana-ai</a> by <a
  href="https://footloose.io">footloose labs</a>
plugins:
  - search
  - mermaid2:
      version: 8.14.0
markdown_extensions:
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.extra
  - pymdownx.arithmatex:
      generic: true
nav:
  - Introduction: index.md
  - BigLetter:
      - Big-Index: bigletter/big-index.md
  - Brands:
      - one-rename: brands/one-rename.md
  - test: test.md
  - testu:
      - rename-test: testu/rename-test.md
      - test33: testu/test33.md
  - CSVToArray: CSVToArray.md
  - TextToAbstraction: texttoabstraction.md
  - Math Formula: math formula.md
  - CSVToJSON: CSVToJSON.md
  - HSBToRGB: HSBToRGB.md
  - HSLToRGB: HSLToRGB.md
  - JSONToFile: JSONToFile.md
  - JSONtoCSV: JSONtoCSV.md
  - RGBToHSB: RGBToHSB.md
  - RGBToHSL: RGBToHSL.md
  - RGBToHex: RGBToHex.md
  - URLJoin: URLJoin.md
  - UUIDGeneratorBrowser: UUIDGeneratorBrowser.md
  - UUIDGeneratorNode: UUIDGeneratorNode.md
  - accumulate: accumulate.md
  - addClass: addClass.md
  - addDaysToDate: addDaysToDate.md
  - addEventListenerAll: addEventListenerAll.md
  - addMinutesToDate: addMinutesToDate.md
  - addMultipleEvents: addMultipleEvents.md
  - addStyles: addStyles.md
  - addWeekDays: addWeekDays.md
  - all: all.md
  - allEqual: allEqual.md
  - allEqualBy: allEqualBy.md
  - allUnique: allUnique.md
  - allUniqueBy: allUniqueBy.md
  - and: and.md
  - any: any.md
  - aperture: aperture.md
  - approximatelyEqual: approximatelyEqual.md
  - arithmeticProgression: arithmeticProgression.md
  - arrayToCSV: arrayToCSV.md
  - arrayToHTMLList: arrayToHTMLList.md
  - ary: ary.md
  - assertValidKeys: assertValidKeys.md
  - atob: atob.md
  - attempt: attempt.md
  - average: average.md
  - averageBy: averageBy.md
  - bifurcate: bifurcate.md
  - bifurcateBy: bifurcateBy.md
  - binary: binary.md
  - binarySearch: binarySearch.md
  - bind: bind.md
  - bindAll: bindAll.md
  - bindKey: bindKey.md
  - binomialCoefficient: binomialCoefficient.md
  - both: both.md
  - bottomVisible: bottomVisible.md
  - btoa: btoa.md
  - bubbleSort: bubbleSort.md
  - bucketSort: bucketSort.md
  - byteSize: byteSize.md
  - caesarCipher: caesarCipher.md
  - call: call.md
  - callOrReturn: callOrReturn.md
  - capitalize: capitalize.md
  - capitalizeEveryWord: capitalizeEveryWord.md
  - cartesianProduct: cartesianProduct.md
  - castArray: castArray.md
  - celsiusToFahrenheit: celsiusToFahrenheit.md
  - chainAsync: chainAsync.md
  - changeLightness: changeLightness.md
  - checkProp: checkProp.md
  - chunk: chunk.md
  - chunkIntoN: chunkIntoN.md
  - chunkify: chunkify.md
  - clampNumber: clampNumber.md
  - cloneRegExp: cloneRegExp.md
  - closest: closest.md
  - coalesce: coalesce.md
  - coalesceFactory: coalesceFactory.md
  - collectInto: collectInto.md
  - colorize: colorize.md
  - combine: combine.md
  - commonKeys: commonKeys.md
  - compact: compact.md
  - compactJoin: compactJoin.md
  - compactObject: compactObject.md
  - compactWhitespace: compactWhitespace.md
  - complement: complement.md
  - compose: compose.md
  - composeRight: composeRight.md
  - containsWhitespace: containsWhitespace.md
  - converge: converge.md
  - copySign: copySign.md
  - copyToClipboard: copyToClipboard.md
  - copyToClipboardAsync: copyToClipboardAsync.md
  - countBy: countBy.md
  - countOccurrences: countOccurrences.md
  - countSubstrings: countSubstrings.md
  - countWeekDaysBetween: countWeekDaysBetween.md
  - counter: counter.md
  - createDirIfNotExists: createDirIfNotExists.md
  - createElement: createElement.md
  - createEventHub: createEventHub.md
  - currentURL: currentURL.md
  - curry: curry.md
  - cycleGenerator: cycleGenerator.md
  - dateRangeGenerator: dateRangeGenerator.md
  - dayName: dayName.md
  - dayOfYear: dayOfYear.md
  - daysAgo: daysAgo.md
  - daysFromNow: daysFromNow.md
  - daysInMonth: daysInMonth.md
  - debounce: debounce.md
  - debouncePromise: debouncePromise.md
  - decapitalize: decapitalize.md
  - deepClone: deepClone.md
  - deepFlatten: deepFlatten.md
  - deepFreeze: deepFreeze.md
  - deepGet: deepGet.md
  - deepMapKeys: deepMapKeys.md
  - deepMerge: deepMerge.md
  - defaults: defaults.md
  - defer: defer.md
  - degreesToRads: degreesToRads.md
  - delay: delay.md
  - detectDeviceType: detectDeviceType.md
  - detectLanguage: detectLanguage.md
  - difference: difference.md
  - differenceBy: differenceBy.md
  - differenceWith: differenceWith.md
  - dig: dig.md
  - digitize: digitize.md
  - distance: distance.md
  - divmod: divmod.md
  - drop: drop.md
  - dropRight: dropRight.md
  - dropRightWhile: dropRightWhile.md
  - dropWhile: dropWhile.md
  - either: either.md
  - elementContains: elementContains.md
  - elementIsFocused: elementIsFocused.md
  - elementIsVisibleInViewport: elementIsVisibleInViewport.md
  - equals: equals.md
  - escapeHTML: escapeHTML.md
  - escapeRegExp: escapeRegExp.md
  - euclideanDistance: euclideanDistance.md
  - everyNth: everyNth.md
  - expandTabs: expandTabs.md
  - extendHex: extendHex.md
  - factorial: factorial.md
  - fahrenheitToCelsius: fahrenheitToCelsius.md
  - fibonacci: fibonacci.md
  - filterNonUnique: filterNonUnique.md
  - filterNonUniqueBy: filterNonUniqueBy.md
  - filterUnique: filterUnique.md
  - filterUniqueBy: filterUniqueBy.md
  - findClosestAnchor: findClosestAnchor.md
  - findClosestMatchingNode: findClosestMatchingNode.md
  - findConsecutive: findConsecutive.md
  - findFirstN: findFirstN.md
  - findKey: findKey.md
  - findKeys: findKeys.md
  - findLast: findLast.md
  - findLastIndex: findLastIndex.md
  - findLastKey: findLastKey.md
  - findLastN: findLastN.md
  - flags: flags.md
  - flatIterator: flatIterator.md
  - flatten: flatten.md
  - flattenObject: flattenObject.md
  - flip: flip.md
  - forEachRight: forEachRight.md
  - forOwn: forOwn.md
  - forOwnRight: forOwnRight.md
  - formToObject: formToObject.md
  - formatDuration: formatDuration.md
  - formatNumber: formatNumber.md
  - formatSeconds: formatSeconds.md
  - frequencies: frequencies.md
  - fromCamelCase: fromCamelCase.md
  - fromTimestamp: fromTimestamp.md
  - frozenSet: frozenSet.md
  - fullscreen: fullscreen.md
  - functionName: functionName.md
  - functions: functions.md
  - gcd: gcd.md
  - generateItems: generateItems.md
  - generateUntil: generateUntil.md
  - generateWhile: generateWhile.md
  - generatorToArray: generatorToArray.md
  - geometricProgression: geometricProgression.md
  - get: get.md
  - getAncestors: getAncestors.md
  - getBaseURL: getBaseURL.md
  - getCmdArgs: getCmdArgs.md
  - getColonTimeFromDate: getColonTimeFromDate.md
  - getDaysDiffBetweenDates: getDaysDiffBetweenDates.md
  - getElementsBiggerThanViewport: getElementsBiggerThanViewport.md
  - getHoursDiffBetweenDates: getHoursDiffBetweenDates.md
  - getImages: getImages.md
  - getMeridiemSuffixOfInteger: getMeridiemSuffixOfInteger.md
  - getMinutesDiffBetweenDates: getMinutesDiffBetweenDates.md
  - getMonthsDiffBetweenDates: getMonthsDiffBetweenDates.md
  - getParentsUntil: getParentsUntil.md
  - getProtocol: getProtocol.md
  - getScrollPosition: getScrollPosition.md
  - getSecondsDiffBetweenDates: getSecondsDiffBetweenDates.md
  - getSelectedText: getSelectedText.md
  - getSiblings: getSiblings.md
  - getStyle: getStyle.md
  - getTimestamp: getTimestamp.md
  - getType: getType.md
  - getURLParameters: getURLParameters.md
  - getVerticalOffset: getVerticalOffset.md
  - groupBy: groupBy.md
  - hammingDistance: hammingDistance.md
  - hasClass: hasClass.md
  - hasDecimals: hasDecimals.md
  - hasDuplicates: hasDuplicates.md
  - hasFlags: hasFlags.md
  - hasKey: hasKey.md
  - hasMany: hasMany.md
  - hasOne: hasOne.md
  - hashBrowser: hashBrowser.md
  - hashNode: hashNode.md
  - haveSameContents: haveSameContents.md
  - head: head.md
  - heapsort: heapsort.md
  - hexToRGB: hexToRGB.md
  - hide: hide.md
  - httpDelete: httpDelete.md
  - httpGet: httpGet.md
  - httpPost: httpPost.md
  - httpPut: httpPut.md
  - httpsRedirect: httpsRedirect.md
  - hz: hz.md
  - inRange: inRange.md
  - includesAll: includesAll.md
  - includesAny: includesAny.md
  - indentString: indentString.md
  - index: index.md
  - indexBy: indexBy.md
  - indexOfAll: indexOfAll.md
  - indexOfSubstrings: indexOfSubstrings.md
  - indexOn: indexOn.md
  - initial: initial.md
  - initialize2DArray: initialize2DArray.md
  - initializeArrayWithRange: initializeArrayWithRange.md
  - initializeArrayWithRangeRight: initializeArrayWithRangeRight.md
  - initializeArrayWithValues: initializeArrayWithValues.md
  - initializeNDArray: initializeNDArray.md
  - injectCSS: injectCSS.md
  - insertAfter: insertAfter.md
  - insertAt: insertAt.md
  - insertBefore: insertBefore.md
  - insertionSort: insertionSort.md
  - intersection: intersection.md
  - intersectionBy: intersectionBy.md
  - intersectionWith: intersectionWith.md
  - invertKeyValues: invertKeyValues.md
  - is: is.md
  - isAbsoluteURL: isAbsoluteURL.md
  - isAfterDate: isAfterDate.md
  - isAlpha: isAlpha.md
  - isAlphaNumeric: isAlphaNumeric.md
  - isAnagram: isAnagram.md
  - isArrayLike: isArrayLike.md
  - isAsyncFunction: isAsyncFunction.md
  - isBeforeDate: isBeforeDate.md
  - isBetweenDates: isBetweenDates.md
  - isBoolean: isBoolean.md
  - isBrowser: isBrowser.md
  - isBrowserTabFocused: isBrowserTabFocused.md
  - isContainedIn: isContainedIn.md
  - isDateValid: isDateValid.md
  - isDeepFrozen: isDeepFrozen.md
  - isDisjoint: isDisjoint.md
  - isDivisible: isDivisible.md
  - isDuplexStream: isDuplexStream.md
  - isEmpty: isEmpty.md
  - isEven: isEven.md
  - isFunction: isFunction.md
  - isGeneratorFunction: isGeneratorFunction.md
  - isISOString: isISOString.md
  - isLeapYear: isLeapYear.md
  - isLocalStorageEnabled: isLocalStorageEnabled.md
  - isLowerCase: isLowerCase.md
  - isNegativeZero: isNegativeZero.md
  - isNil: isNil.md
  - isNode: isNode.md
  - isNull: isNull.md
  - isNumber: isNumber.md
  - isObject: isObject.md
  - isObjectLike: isObjectLike.md
  - isOdd: isOdd.md
  - isPlainObject: isPlainObject.md
  - isPowerOfTen: isPowerOfTen.md
  - isPowerOfTwo: isPowerOfTwo.md
  - isPrime: isPrime.md
  - isPrimitive: isPrimitive.md
  - isPromiseLike: isPromiseLike.md
  - isReadableStream: isReadableStream.md
  - isSameDate: isSameDate.md
  - isSameOrigin: isSameOrigin.md
  - isSessionStorageEnabled: isSessionStorageEnabled.md
  - isSorted: isSorted.md
  - isStream: isStream.md
  - isString: isString.md
  - isSymbol: isSymbol.md
  - isTravisCI: isTravisCI.md
  - isUndefined: isUndefined.md
  - isUpperCase: isUpperCase.md
  - isValidJSON: isValidJSON.md
  - isWeekday: isWeekday.md
  - isWeekend: isWeekend.md
  - isWritableStream: isWritableStream.md
  - join: join.md
  - juxt: juxt.md
  - kMeans: kMeans.md
  - kNearestNeighbors: kNearestNeighbors.md
  - kmToMiles: kmToMiles.md
  - last: last.md
  - lastDateOfMonth: lastDateOfMonth.md
  - lcm: lcm.md
  - levenshteinDistance: levenshteinDistance.md
  - linearSearch: linearSearch.md
  - listenOnce: listenOnce.md
  - logBase: logBase.md
  - logo: logo.png
  - longestItem: longestItem.md
  - lowercaseKeys: lowercaseKeys.md
  - luhnCheck: luhnCheck.md
  - mapConsecutive: mapConsecutive.md
  - mapKeys: mapKeys.md
  - mapNumRange: mapNumRange.md
  - mapObject: mapObject.md
  - mapString: mapString.md
  - mapValues: mapValues.md
  - mask: mask.md
  - matches: matches.md
  - matchesWith: matchesWith.md
  - maxBy: maxBy.md
  - maxDate: maxDate.md
  - maxN: maxN.md
  - median: median.md
  - memoize: memoize.md
  - merge: merge.md
  - mergeSort: mergeSort.md
  - mergeSortedArrays: mergeSortedArrays.md
  - midpoint: midpoint.md
  - milesToKm: milesToKm.md
  - minBy: minBy.md
  - minDate: minDate.md
  - minN: minN.md
  - mostFrequent: mostFrequent.md
  - mostPerformant: mostPerformant.md
  - negate: negate.md
  - nest: nest.md
  - nodeListToArray: nodeListToArray.md
  - none: none.md
  - nor: nor.md
  - normalizeLineEndings: normalizeLineEndings.md
  - not: not.md
  - nthArg: nthArg.md
  - nthElement: nthElement.md
  - nthRoot: nthRoot.md
  - objectFromPairs: objectFromPairs.md
  - objectToEntries: objectToEntries.md
  - objectToPairs: objectToPairs.md
  - objectToQueryString: objectToQueryString.md
  - observeMutations: observeMutations.md
  - 'off': off.md
  - offset: offset.md
  - omit: omit.md
  - omitBy: omitBy.md
  - 'on': on.md
  - onClickOutside: onClickOutside.md
  - onScrollStop: onScrollStop.md
  - onUserInputChange: onUserInputChange.md
  - once: once.md
  - or: or.md
  - orderBy: orderBy.md
  - orderWith: orderWith.md
  - over: over.md
  - overArgs: overArgs.md
  - pad: pad.md
  - padNumber: padNumber.md
  - palindrome: palindrome.md
  - parseCookie: parseCookie.md
  - partial: partial.md
  - partialRight: partialRight.md
  - partition: partition.md
  - partitionBy: partitionBy.md
  - percentile: percentile.md
  - permutations: permutations.md
  - pick: pick.md
  - pickBy: pickBy.md
  - pipeAsyncFunctions: pipeAsyncFunctions.md
  - pipeFunctions: pipeFunctions.md
  - pluck: pluck.md
  - pluralize: pluralize.md
  - powerset: powerset.md
  - prefersDarkColorScheme: prefersDarkColorScheme.md
  - prefersLightColorScheme: prefersLightColorScheme.md
  - prefix: prefix.md
  - prettyBytes: prettyBytes.md
  - primeFactors: primeFactors.md
  - primes: primes.md
  - prod: prod.md
  - promisify: promisify.md
  - pull: pull.md
  - pullAtIndex: pullAtIndex.md
  - pullAtValue: pullAtValue.md
  - pullBy: pullBy.md
  - quarterOfYear: quarterOfYear.md
  - queryStringToObject: queryStringToObject.md
  - quickSort: quickSort.md
  - radsToDegrees: radsToDegrees.md
  - randomAlphaNumeric: randomAlphaNumeric.md
  - randomBoolean: randomBoolean.md
  - randomHexColorCode: randomHexColorCode.md
  - randomIntArrayInRange: randomIntArrayInRange.md
  - randomIntegerInRange: randomIntegerInRange.md
  - randomNumberInRange: randomNumberInRange.md
  - rangeGenerator: rangeGenerator.md
  - ranking: ranking.md
  - readFileLines: readFileLines.md
  - rearg: rearg.md
  - recordAnimationFrames: recordAnimationFrames.md
  - redirect: redirect.md
  - reduceSuccessive: reduceSuccessive.md
  - reduceWhich: reduceWhich.md
  - reducedFilter: reducedFilter.md
  - reject: reject.md
  - remove: remove.md
  - removeAccents: removeAccents.md
  - removeClass: removeClass.md
  - removeElement: removeElement.md
  - removeEventListenerAll: removeEventListenerAll.md
  - removeNonASCII: removeNonASCII.md
  - removeWhitespace: removeWhitespace.md
  - renameKeys: renameKeys.md
  - renderElement: renderElement.md
  - repeatGenerator: repeatGenerator.md
  - replaceLast: replaceLast.md
  - requireUncached: requireUncached.md
  - resolveAfter: resolveAfter.md
  - reverseNumber: reverseNumber.md
  - reverseString: reverseString.md
  - round: round.md
  - runAsync: runAsync.md
  - runPromisesInSeries: runPromisesInSeries.md
  - sample: sample.md
  - sampleSize: sampleSize.md
  - scrollToTop: scrollToTop.md
  - sdbm: sdbm.md
  - selectionSort: selectionSort.md
  - serializeCookie: serializeCookie.md
  - serializeForm: serializeForm.md
  - setStyle: setStyle.md
  - shallowClone: shallowClone.md
  - shank: shank.md
  - show: show.md
  - shuffle: shuffle.md
  - similarity: similarity.md
  - size: size.md
  - sleep: sleep.md
  - slugify: slugify.md
  - smoothScroll: smoothScroll.md
  - sortCharactersInString: sortCharactersInString.md
  - sortedIndex: sortedIndex.md
  - sortedIndexBy: sortedIndexBy.md
  - sortedLastIndex: sortedLastIndex.md
  - sortedLastIndexBy: sortedLastIndexBy.md
  - splitLines: splitLines.md
  - spreadOver: spreadOver.md
  - stableSort: stableSort.md
  - standardDeviation: standardDeviation.md
  - stringPermutations: stringPermutations.md
  - stringifyCircularJSON: stringifyCircularJSON.md
  - stripHTMLTags: stripHTMLTags.md
  - subSet: subSet.md
  - sum: sum.md
  - sumBy: sumBy.md
  - sumN: sumN.md
  - sumPower: sumPower.md
  - superSet: superSet.md
  - supportsTouchEvents: supportsTouchEvents.md
  - swapCase: swapCase.md
  - symbolizeKeys: symbolizeKeys.md
  - symmetricDifference: symmetricDifference.md
  - symmetricDifferenceBy: symmetricDifferenceBy.md
  - symmetricDifferenceWith: symmetricDifferenceWith.md
  - tail: tail.md
  - take: take.md
  - takeRight: takeRight.md
  - takeRightUntil: takeRightUntil.md
  - takeRightWhile: takeRightWhile.md
  - takeUntil: takeUntil.md
  - takeWhile: takeWhile.md
  - throttle: throttle.md
  - timeTaken: timeTaken.md
  - times: times.md
  - toCamelCase: toCamelCase.md
  - toCharArray: toCharArray.md
  - toCurrency: toCurrency.md
  - toDecimalMark: toDecimalMark.md
  - toHSLArray: toHSLArray.md
  - toHSLObject: toHSLObject.md
  - toHash: toHash.md
  - toISOStringWithTimezone: toISOStringWithTimezone.md
  - toKebabCase: toKebabCase.md
  - toOptionalFixed: toOptionalFixed.md
  - toOrdinalSuffix: toOrdinalSuffix.md
  - toPairs: toPairs.md
  - toPascalCase: toPascalCase.md
  - toRGBArray: toRGBArray.md
  - toRGBObject: toRGBObject.md
  - toRomanNumeral: toRomanNumeral.md
  - toSafeInteger: toSafeInteger.md
  - toSnakeCase: toSnakeCase.md
  - toTitleCase: toTitleCase.md
  - toggleClass: toggleClass.md
  - toggleElement: toggleElement.md
  - tomorrow: tomorrow.md
  - transform: transform.md
  - transpose: transpose.md
  - triggerEvent: triggerEvent.md
  - truncateString: truncateString.md
  - truncateStringAtWhitespace: truncateStringAtWhitespace.md
  - truthCheckCollection: truthCheckCollection.md
  - unary: unary.md
  - uncurry: uncurry.md
  - unescapeHTML: unescapeHTML.md
  - unflattenObject: unflattenObject.md
  - unfold: unfold.md
  - union: union.md
  - unionBy: unionBy.md
  - unionWith: unionWith.md
  - uniqueElements: uniqueElements.md
  - uniqueElementsBy: uniqueElementsBy.md
  - uniqueElementsByRight: uniqueElementsByRight.md
  - uniqueSymmetricDifference: uniqueSymmetricDifference.md
  - untildify: untildify.md
  - unwind: unwind.md
  - unzip: unzip.md
  - unzipWith: unzipWith.md
  - validateNumber: validateNumber.md
  - vectorAngle: vectorAngle.md
  - vectorDistance: vectorDistance.md
  - walkThrough: walkThrough.md
  - weekOfYear: weekOfYear.md
  - weightedAverage: weightedAverage.md
  - weightedSample: weightedSample.md
  - when: when.md
  - without: without.md
  - wordWrap: wordWrap.md
  - words: words.md
  - xProd: xProd.md
  - xor: xor.md
  - yesNo: yesNo.md
  - yesterday: yesterday.md
  - zip: zip.md
  - zipObject: zipObject.md
  - zipWith: zipWith.md
extra:
  generator: false
  social:
    - link: ''
      icon: fontawesome/brands/instagram
    - link: https://github.com/30-second
      icon: fontawesome/brands/github
